"use client";

/**
 * Home page -- Root entry point for the CAD Cursor application.
 *
 * Layout architecture (futuristic white/violet theme):
 *   - Viewport fills the entire screen as a background layer (fixed, inset-0)
 *   - ChatPanel floats on the RIGHT as a glass-morphism island (~400px wide)
 *   - Toggle button reveals/hides the chat island with smooth slide animation
 *   - Drag-to-resize handle on the left edge of the island
 *
 * Owns the shared `jscadCode` state that connects the chat panel
 * (which fetches code from the API) to the viewport (which renders it).
 */

import { useState, useRef, useCallback, useEffect, useMemo } from "react";
import ChatPanel from "@/components/chat/ChatPanel";
import Viewport from "@/components/viewport/Viewport";

/* ---- Constants ---- */
const MIN_PANEL_WIDTH = 320;
const MAX_PANEL_WIDTH = 600;
const DEFAULT_PANEL_WIDTH = 400;
const EDGE_MARGIN = 20; /* px margin from viewport edges */

/* ---- God Mode: pre-validated JSCAD for demo safety net (Cmd+Shift+G) ---- */
const GOD_MODE_CODE = `
// Mechanical bearing housing — visually impressive demo piece
const base = cuboid({ size: [12, 3, 8] });
const bearingOuter = cylinder({ radius: 3, height: 4, segments: 48 });
const bearingInner = cylinder({ radius: 1.5, height: 5, segments: 48 });
const bearing = subtract(bearingOuter, bearingInner);
const bearingMounted = translate([0, 3.5, 0], bearing);

const mountHole1 = cylinder({ radius: 0.6, height: 4, segments: 24 });
const mountHole2 = cylinder({ radius: 0.6, height: 4, segments: 24 });
const hole1 = translate([-4.5, 0, -2.5], mountHole1);
const hole2 = translate([-4.5, 0, 2.5], mountHole2);
const hole3 = translate([4.5, 0, -2.5], mountHole1);
const hole4 = translate([4.5, 0, 2.5], mountHole2);

const ribLeft = cuboid({ size: [1, 4, 1] });
const ribRight = cuboid({ size: [1, 4, 1] });
const rib1 = translate([-3, 2, 0], ribLeft);
const rib2 = translate([3, 2, 0], ribRight);

const body = union(base, bearingMounted, rib1, rib2);
return subtract(body, hole1, hole2, hole3, hole4);
`;


export default function Home() {
  /* Shared state: JSCAD code generated by Claude, consumed by Viewport */
  const [jscadCode, setJscadCode] = useState<string | null>(null);

  /* Last user prompt — used as basis for export filename */
  const [lastPrompt, setLastPrompt] = useState<string | null>(null);

  /* Whether the AI is currently generating — drives viewport loading overlay */
  const [isGenerating, setIsGenerating] = useState(false);

  /* Chat island visibility and width */
  const [chatOpen, setChatOpen] = useState(true);
  const [panelWidth, setPanelWidth] = useState(DEFAULT_PANEL_WIDTH);

  /* Hover zone: show toggle button when mouse is near right edge */
  const [showToggle, setShowToggle] = useState(false);

  /* Resize drag state */
  const isDragging = useRef(false);
  const startX = useRef(0);
  const startWidth = useRef(DEFAULT_PANEL_WIDTH);

  /* ---- Resize handlers ---- */
  const onResizeStart = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault();
      isDragging.current = true;
      startX.current = e.clientX;
      startWidth.current = panelWidth;
      document.body.style.cursor = "col-resize";
      document.body.style.userSelect = "none";
    },
    [panelWidth]
  );

  /* ---- God mode shortcut: Cmd+Shift+G (Mac) / Ctrl+Shift+G (Win) ---- */
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.shiftKey && e.key === "g") {
        e.preventDefault();
        setJscadCode(GOD_MODE_CODE);
        setLastPrompt("Mechanical bearing housing");
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  useEffect(() => {
    const onMouseMove = (e: MouseEvent) => {
      if (!isDragging.current) return;
      /* Dragging left = larger panel, so subtract delta */
      const delta = startX.current - e.clientX;
      const newWidth = Math.min(
        MAX_PANEL_WIDTH,
        Math.max(MIN_PANEL_WIDTH, startWidth.current + delta)
      );
      setPanelWidth(newWidth);
    };

    const onMouseUp = () => {
      if (isDragging.current) {
        isDragging.current = false;
        document.body.style.cursor = "";
        document.body.style.userSelect = "";
      }
    };

    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", onMouseUp);
    return () => {
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("mouseup", onMouseUp);
    };
  }, []);

  const viewportEl = useMemo(
    () => <Viewport jscadCode={jscadCode} modelDescription={lastPrompt} />,
    [jscadCode, lastPrompt],
  );

  const chatPanelEl = useMemo(
    () => <ChatPanel onCodeGenerated={setJscadCode} onGeneratingChange={setIsGenerating} currentCode={jscadCode} onPromptSent={setLastPrompt} />,
    [jscadCode],
  );

  return (
    <div className="relative h-screen w-screen overflow-hidden bg-[#f7f7fb]">
      {/* ======================================
          Viewport -- Full-bleed background layer
          ====================================== */}
      <div className="absolute inset-0 z-0">
        {viewportEl}
      </div>

      {/* ======================================
          Right-edge hover zone -- reveals toggle
          ====================================== */}
      <div
        className="absolute right-0 top-0 z-30 h-full w-16"
        onMouseEnter={() => setShowToggle(true)}
        onMouseLeave={() => setShowToggle(false)}
      />

      {/* ======================================
          Toggle button -- small pill that slides
          with the panel open/close state
          ====================================== */}
      <button
        onClick={() => setChatOpen((prev) => !prev)}
        onMouseEnter={() => setShowToggle(true)}
        onMouseLeave={() => setShowToggle(false)}
        aria-label={chatOpen ? "Close chat" : "Open chat"}
        className={`
          absolute z-40 top-1/2 -translate-y-1/2
          flex h-10 w-6 items-center justify-center
          rounded-l-lg bg-white/80 backdrop-blur-md
          border border-r-0 border-gray-200 shadow-lg
          text-gray-500 hover:text-violet-500
          transition-all duration-300 ease-in-out
          ${
            chatOpen
              ? ""
              : showToggle
                ? "opacity-100"
                : "opacity-0 pointer-events-none"
          }
        `}
        style={{
          right: chatOpen
            ? `${panelWidth + EDGE_MARGIN}px`
            : "0px",
        }}
      >
        {/* Chevron icon -- flips based on state */}
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 20 20"
          fill="currentColor"
          className={`h-4 w-4 transition-transform duration-300 ${
            chatOpen ? "rotate-0" : "rotate-180"
          }`}
        >
          <path
            fillRule="evenodd"
            d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
            clipRule="evenodd"
          />
        </svg>
      </button>

      {/* ======================================
          Chat island -- Floating glass-morphism
          panel on the right side
          ====================================== */}
      <aside
        className={`
          absolute z-30 flex flex-col
          rounded-2xl shadow-2xl
          bg-white/70 backdrop-blur-xl
          border border-white/50
          overflow-hidden
          transition-all duration-300 ease-in-out
          ${chatOpen ? "translate-x-0 opacity-100" : "translate-x-[120%] opacity-0"}
        `}
        style={{
          top: EDGE_MARGIN,
          right: EDGE_MARGIN,
          bottom: EDGE_MARGIN,
          width: panelWidth,
        }}
      >
        {/* ---- Resize handle: thin bar on left edge ---- */}
        <div
          onMouseDown={onResizeStart}
          className="
            absolute left-0 top-0 bottom-0 z-50 w-1.5
            cursor-col-resize hover:bg-violet-400/30
            transition-colors duration-150
          "
        />

        {/* ---- Chat panel content ---- */}
        {chatPanelEl}
      </aside>
    </div>
  );
}
